name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)  # Get the short commit hash
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/api:$COMMIT_ID"
          echo "Building Docker image with tag: $IMAGE_TAG"
          docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: List Docker images
        run: |
          docker images

      - name: Push Docker Image
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)  # Get the short commit hash
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/api:$COMMIT_ID"
          echo "Pushing Docker image with tag: $IMAGE_TAG"
          docker push $IMAGE_TAG   
